######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 11 15:16:58 2007
######################################################################

QT+=xml
CONFIG+=console
INCLUDEPATH+=../../include
unix{ 
    LIBS+=../../lib/libxmm2.so
}
win32 {
    LIBS+=../../lib/xmm20.dll
}
DESTDIR=./release
MOC_DIR=./compilation
OBJECTS_DIR=./compilation
RCC_DIR=./compilation
UI_DIR=./compilation
UI_HEADERS_DIR=./compilation
UI_SOURCES_DIR=./compilation
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
